---
- name: Remove old docker package
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ old_docker_packages }}"

- name: Add debian docker repository
  become: yes
  block:
  - name: Add docker GPG key
    apt_key:
      url: "{{ docker_gpg_key_url }}"
      id: "{{ docker_gpg_key }}"
      state: present

  - name: Add docker repository
    apt_repository:
      repo: "{{ docker_repo }}"
      state: present
      update_cache: yes
  when: ansible_os_family | lower == 'debian'

- name: Install docker package
  become: true
  package:
    name: "{{ docker_package }}"
    state: present
    update_cache: true
  register: result
  retries: 3
  until: result is succeeded
