---
- name: Add users to docker group
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  when: docker_users | length > 0

- name: Enable docker daemon startup
  block:
  - name: Enable docker on system startup
    become: yes
    systemd:
      name: docker
      enabled: true
    notify:
      - restart docker daemon

  - name: Ensure docker daemon is running
    become: yes
    service:
      name: docker
      state: started
  when: enable_docker_daemon | bool

- name: Disable docker daemon startup
  block:
  - name: Disable docker from system startup
    become: yes
    systemd:
      name: docker
      enabled: false
    notify:
      - stop docker daemon

  - name: Ensure docker daemon is stopped
    become: yes
    service:
      name: docker
      state: stopped
  when: not enable_docker_daemon | bool
