---
- name: Remove legacy docker packages
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker.legacy_packages }}"

- name: Add debian docker repository
  become: yes
  block:
  - name: Add docker GPG key
    apt_key:
      url: "{{ docker.gpg_key_url }}"
      id: "{{ docker.gpg_key }}"
      state: present

  - name: Add docker repository
    apt_repository:
      repo: "{{ docker.apt_repo }}"
      state: present
      update_cache: yes
  when: ansible_os_family | lower == 'debian'

- name: Install docker package
  become: true
  package:
    name: "{{ docker.package_name }}"
    state: present
    update_cache: true
  register: result
  retries: 3
  until: result is succeeded

- name: Create .dockerrc file
  template:
    src: dockerrc.j2
    dest: "{{ ansible_env.HOME }}/.dockerrc"
    mode: 0644

- name: Verify docker installation
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /etc/systemd/system
