---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml

- name: Set apt to use https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: Install system dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: result
  retries: 3
  until: result is succeeded
  with_items: "{{ system_dependencies }}"

- include_tasks: install-docker.yml

- include_tasks: configure-docker.yml

- include_tasks: install-compose.yml
  when: install_compose | bool

- include_tasks: install-kubectl.yml
  when: install_kubectl | bool

- include_tasks: configure-shell.yml
