---
- name: restart docker daemon
  become: true
  systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: stop docker daemon
  become: true
  systemd:
    name: docker
    state: stopped
    daemon_reload: false
