---
- name: docker daemon enabled
  become: true
  systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: docker daemon disabled
  become: true
  systemd:
    name: docker
    state: stopped
    daemon_reload: false
